SELECT 
  e.FIRST_NAME || ' ' || e.LAST_NAME as NAME
  ,d.NAME as DEPARTMENT_NAME
  ,t.NAME as GROUP_NAME
  
FROM 
  EMPLOYEE AS e INNER JOIN TEAM AS t ON
    e.GROUP_ID = t.ID
  INNER JOIN DEPARTMENT AS d ON
    t.DEPARTMENT_ID = d.ID;
