SELECT 
  t.ID as TEAM_ID
  ,SUM(s.EARNING) TOTAL_EARNING

FROM
  SALES AS s INNER JOIN EMPLOYEE AS e ON
    s.EMP_ID = e.ID
  INNER JOIN TEAM AS t ON
    e.GROUP_ID = t.ID

WHERE
  t.ID IN ('T0001','T0002','T0003')

GROUP BY t.ID;